FROM python:3
ENV PYTHONUNBUFFERED 1

# Create code source code folder
RUN mkdir /code
WORKDIR /code

# Install python packet
ADD requirements.txt /code
RUN pip install -r requirements.txt

# Copy source code to docker
ADD . /code/
